name: blognikola
dependencies:
- blinker=1.4=py35_0
- cloudpickle=0.2.1=py35_0
- docutils=0.12=py35_2
- doit=0.29.0=py35_0
- freetype=2.5.5=1
- husl=4.0.3=py35_0
- jbig=2.1=0
- jpeg=8d=2
- libpng=1.6.22=0
- libtiff=4.0.6=1
- libxml2=2.9.2=1
- libxslt=1.1.28=2
- logbook=0.11.2=py35_0
- lxml=3.6.0=py35_0
- macfsevents=0.4=py35_0
- mako=1.0.4=py35_0
- markupsafe=0.23=py35_2
- natsort=4.0.3=py35_0
- nikola=7.7.3=py35_0
- openssl=1.0.2h=1
- pillow=3.2.0=py35_0
- pip=8.1.2=py35_0
- pygments=2.1.3=py35_0
- pyrss2gen=1.1=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- readline=6.2=2
- requests=2.10.0=py35_0
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- unidecode=0.04.19=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yapsy=1.11.223=py35_0
- zlib=1.2.8=3
- pip:
  - arrow==0.7.0
  - binaryornot==0.4.0
  - chardet==2.3.0
  - click==6.4
  - cookiecutter==1.4.0
  - future==0.15.2
  - jinja2-time==0.1.0
  - poyo==0.1.0
  - whichcraft==0.1.1

